name: adzuna-mcp
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.13
  - pip
  - pip:
    - fastapi>=0.115.0
    - fastapi-mcp>=0.4.0
    - uvicorn>=0.32.0
    - requests>=2.32.0
    - pydantic>=2.0.0
    - pytest>=8.0.0
    - pytest-cov>=4.1.0
    - pytest-asyncio>=0.23.0
    - requests-mock>=1.11.0
    - httpx>=0.25.0
    - pytest-mock>=3.12.0
